### ISSUE TITLE
Ubuntu 16: Failure to open and initiate saved project

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/Seg3D#236] opened 2017-08-30 11:55 UTC
Seg3D does not properly load a saved project on Ubuntu 16 through all import options. 

1. If you load a project using the file tab once Seg3D is opened, it was say that the project was succesfully imported, but no data is initiated. Or it will return an axial view error saying that it does not work. 
2. If you try to open through the project icon, there is an error. 
3. Loading from the flash screen by double clicking a project in viewer list returns "nrrd error: trouble" at the bottom. 
4. Loading from the flash screen using open project does the same as (1).

**Comment by mildewey** [comment] 2017-11-01 19:19
K, I'm trying to reproduce your issue on the master branch. I created a simple project based on the sample data, saved it and was able to open it through various means. I would like to get more details from you about your project as there may be more specific issues with loading the data in your project. The smoking gun suggesting it may be specific to your data files is the nrrd error you reported. 

If we had more information about which file(s) failed to load and if there was more to that error message, it would be easier to find a fix for you. Is your data shareable? If not, I may be able to make modifications that would help us log issues and track that down from there. Please advise.

**Comment by mildewey** [comment] 2017-11-01 20:51
@kgillette I'm starting work on fixing this issue but cannot directly reproduce it. I am able to create, save, and then open projects on Ubuntu 16.04. The issue you mentioned in 3 above suggests there may be a problem loading specific data files you have in the project. This could be due to a corrupt file or an error in Seg3d loading data files with specific attributes or features. 

To further diagnose the issue, it would be most helpful if you can share your data. Barring that (knowing that your data may be sensitive), we can try to look at the logging Seg3d does to stderr. (I'm happy to give you further direction on capturing the output if needed). Sending us either a file containing that logging or pertinent snippets from the log in a comment below would be helpful.

**Comment by kgillette** [comment] 2017-11-04 17:56
Unfortunately, I cannot share the data with you. However, the nrrd files that are in the project files are generated within Seg3D. Both users can create a new project, do a segmentation from an MRI (no problem reading data), and save a project.  However, the errors occurs when they try to reopen that same project. It could be a problem with the data, but then it might be an error with Seg3D saving files? I also think that even if they were to just start and save a new project without doing any segmentation (so no data loaded), they would get the same problem when trying to load data. 

Would you mind sending me instructions for attaining the information you need? 
I will have them do a Seg3d update, make sure it is still broken, and then send you their output if it is. 

Also, the master branch created an error with my Seg3D where I cannot visualize or do anything with the loaded segmentations. It was working fine until I pulled and rebuilt last week. Should I file a seperate issue? I am running on CentOS 7.

**Comment by mildewey** [comment] 2017-11-07 15:57
The easiest way to capture the data from Seg3d is to run it like this `bin/Seg3D/Seg3D2 &> /tmp/seg3d.log` 
from the terminal, reproduce the issue, and send us the /tmp/seg3d.log file. The log file should only contain anonymous information, but might contain things like file names, so it would be worthwhile checking it an sanitizing it of any sensitive information before sending it over.

If you're having trouble building Seg3D on your Centos machine, please file a separate issue. Naturally, I'll jump over and help you on that as soon as possible so we can subsequently fix this bug.

**Comment by kgillette** [comment] 2017-11-10 10:37
There is nothing outputted to the /tmp/seg3d.log file, but I have taken a screenshot of the error messages when loaded project files in different ways. The nrrd file is one that is saved by seg3d and is not an exnternal nrrd file. I am working with the same data in CentOS 7 and have no issues. 

![screenshot from 2017-11-10 10-39-22](https://user-images.githubusercontent.com/12956701/32654388-56dd0d0e-c60b-11e7-983a-43f4d089cbb7.png)

**Comment by mildewey** [comment] 2017-11-10 16:51
That's exactly what I needed to move forward! (also what I expected to be put in your log file.) I'll start poking around and get back to you.

**Comment by kgillette** [comment] 2017-11-16 08:37
Hi Mark! Just tested it with the angio.nrrd from the Seg3D data set and it loaded, although there was an error. 
![screenshot from 2017-11-16 09-27-20](https://user-images.githubusercontent.com/12956701/32881177-9fed37d6-cab0-11e7-99e9-0352ec42db26.png)

While I can't send you our exact project files, I have included a sample data set that we generated when configuring our MRI scans. Hope that helps! 
[5_VIBE_TRA_IN.zip](https://github.com/SCIInstitute/Seg3D/files/1477814/5_VIBE_TRA_IN.zip)

**Comment by mildewey** [comment] 2017-11-17 17:37
I have a theory, so I want to confirm some things with you.

I imported your sample data above, exported the images (without other segmentation steps) as a nrrd file, then made a new project and imported the nrrd file. I didn't run into any trouble doing that.

If you follow the same steps, do you or your colleagues reproduce the issue? If so, that would be evidence in favor of my suspicions. If not, how would you replicate the issue with the sample data? I will follow your steps and see if the problem is replicated here.

**Comment by kgillette** [comment] 2017-11-23 08:15
Hi Mark! 

Matthias just tested it with the same file I sent you and was unable to load the nrrd. He got the following error:

![seg3d](https://user-images.githubusercontent.com/12956701/33163438-cea11a38-d02e-11e7-998e-13a1a20ffdd1.png)

**Comment by kgillette** [comment] 2017-11-30 08:32
Here is a nrrd file exported by Matthias. I tried opening it on my machine and I get the same import error he was getting. His computer is not set in German, but the nrrd file has the german format of the decimal point using ',' instead of '.' in number. 

[5_VIBE_TRA_IN.nrrd.tar.gz](https://github.com/SCIInstitute/Seg3D/files/1516993/5_VIBE_TRA_IN.nrrd.tar.gz)

**Comment by kgillette** [comment] 2017-11-30 08:32
Maybe it might bve

**Comment by mildewey** [comment] 2017-11-30 16:56
Yes, that's what I had suspected was the cause. I will work on a fix to only export in the US format to avoid this issue in the future.

**Comment by jessdtate** [comment] 2017-12-01 18:46
I tested this on my US mac, and got the same error.  When I changed the decimals to periods, error went away.

**Comment by allywarner** [comment] 2019-03-27 20:40
Hi Karli, is this still an issue?

**Comment by kgillette** [comment] 2019-03-28 07:54
Hello Ally,

I don't believe that it is. I can try to test it when my Ubuntu build is
actually working.

Cheers,
Karli

**Comment by allywarner** [comment] 2019-04-01 17:55
Okie, I’ll close the issue for now and if it’s still a problem you can reopen it!

Thanks!
Ally Warner

I use she/her/hers pronouns - learn more about this here <https://uwm.edu/lgbtrc/support/gender-pronouns/>.

**Closed** 2019-04-01 18:16 UTC
Labels: bug, file export, file import, high priority
